### ISSUE TITLE
Varibale on Playblast

### ISSUE THREAD

**Issue by beyond3dartist** [carlosmu/playblast#1] opened 2022-12-09 06:57 UTC
my issue is
After Playblast if i changed  animation and playblast again... it just replace my old Playblast

I know there is also Version option

**SUGGESTION**

can you add PlayBlast name as Scene or Camera or With Frames using variables

i.e. Scene_01_Cam_01_0001-0125
     Scene_01_0001-0125

so even if i changed my Scene new animation will not be replaced

**Comment by carlosmu** [comment] 2022-12-12 15:21
Hello, I will take note of your request. It would be interesting to have those options.
I will close this issue, since this is not a bug but a feature request.
If you want to support my work you can do it through [Paypal](https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=KJMPUHC8TJRE4).
See you!

**Closed as completed by carlosmu** 2022-12-12 15:21 UTC
